const ROOT = 'diseases';

export const FETCH_DISEASES_REQUEST = `${ROOT}/FETCH_DISEASES_REQUEST`;
export const FETCH_DISEASES_SUCCESS = `${ROOT}/FETCH_DISEASES_SUCCESS`;
export const FETCH_DISEASES_FAILURE = `${ROOT}/FETCH_DISEASES_FAILURE`;