const ROOT = 'medicines';

export const FETCH_MEDICINES_REQUEST = `${ROOT}/FETCH_MEDICINES_REQUEST`;
export const FETCH_MEDICINES_SUCCESS = `${ROOT}/FETCH_MEDICINES_SUCCESS`;
export const FETCH_MEDICINES_FAILURE = `${ROOT}/FETCH_MEDICINES_FAILURE`;